### ISSUE TITLE
Dark Theme is broken in Safari and Edge

### ISSUE THREAD

**Issue by Skrikjo** [vaadin/vaadin-app-layout#116]
# Steps to reproduce

1. Create view that extends from AppLayout and have dark Lumo theme
2. Add tabs.
```
@Route
@PWA(name = "Project Base for Vaadin Flow with Spring", shortName = "Project Base")
@Theme(value = Lumo.class, variant = Lumo.DARK)
public class MainView extends AppLayout {

    public MainView(@Autowired MessageBean bean) {
        Tabs tabs = new Tabs(new Tab("Home"), new Tab("About"));
        tabs.setOrientation(Tabs.Orientation.HORIZONTAL);
        addToNavbar(tabs);
    }

}
```

In Chrome tabs have dark background:
<img width="626" alt="Screenshot 2019-09-04 at 10 08 44" src="https://user-images.githubusercontent.com/42034381/64233175-276c4c00-cefc-11e9-8b1a-0dfb9c3664e5.png">

but in Safari and Edge tabs have light background:
<img width="503" alt="Screenshot 2019-09-04 at 10 08 52" src="https://user-images.githubusercontent.com/42034381/64233200-37842b80-cefc-11e9-9c40-1d273710edba.png">

**Comment by jouni** [comment]
Culprit is here: https://github.com/vaadin/vaadin-app-layout/blob/master/theme/lumo/vaadin-app-layout-styles.html#L32-L44

Also, the next version of Chrome will support `backdrop-filter`, so we should update the code to take use of that as well.

**Comment by jouni** [comment]
I assume you tested using the beta version of macOS Edge, and it already has the updated Chromium with the backdrop filter feature.

**Comment by DiegoCardoso** [comment]
So should we add a custom color for it on the dark mode?

**Comment by jouni** [comment]
It would be awesome if we could use e.g. `rgba(var(--lumo-base-color), 0.8)`, but unfortunately that doesn’t work.

What I’m after visually, is that the navbar would be slightly translucent and visually look like `--lumo-contrast-5pct` on top of `--lumo-base-color`.

**Comment by DiegoCardoso** [comment]
Trying things out here, I could be able to achieve something close to what we have in other browsers by using the same color value of `--lumo-base-color` of the dark variant.
