### ISSUE TITLE
Change argument name 'touchOptimized' to a more fitting name

### ISSUE THREAD

**Issue by mkemmerz** [vaadin/vaadin-app-layout#125]
I was a bit confused about the parameter `touchOptimized` of the method `addToNavbar(boolean touchOptimized, Component... components)`. I thought this parameter would improve the handling of the navbar a lot on mobile devices for example or does something very special on mobile.

In the end the [API documentation](https://vaadin.com/api/platform/14.0.13/com/vaadin/flow/component/applayout/AppLayout.html#addToNavbar-boolean-com.vaadin.flow.component.Component...-) tells:

> touchOptimized - if true, the components will be moved to the bottom navbar area on mobile devices.

Maybe a different name for the parameter would be more fitting because it only changes the navbar to bottom on mobile devices?

**Comment by web-padawan** [comment]
The property does exactly what its name says: [optimizing for touch](https://www.lukew.com/ff/entry.asp?1649).
<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/10589913/69067262-74f05380-0a2b-11ea-9c7f-c6b45925c08d.png">
</td>
<td>
<img src="https://user-images.githubusercontent.com/10589913/69067345-94877c00-0a2b-11ea-8e25-816d58eabbd4.png">
</td>
</tr>
</div>

If you have any better name, feel free to suggest it here and we might consider it.

**Comment by mkemmerz** [comment]
Yes, you are right. The name seems to be far more fitting than I thought so I don't think I can bring up a better one. Ticket can be closed I guess and thanks for the verification, @web-padawan .
