### ISSUE TITLE
Drawer overflow is not handled correctly

### ISSUE THREAD

**Issue by mkn1988** [vaadin/vaadin-app-layout#127]
As shown in [a corresponding app layout flow issue](https://github.com/vaadin/vaadin-app-layout-flow/issues/112) the drawer has no overflow handling. When there are many items in the drawer, they are simply not shown. Adding "overflow-y: scroll;" to the css fixes this quickly, but as a developer I don't want to have to think about this every time, that I use an app-layout.

**Comment by web-padawan** [comment]
Thanks for the issue. Should be easy to fix by adding `overflow: auto;`

We need to check if this affects Material version, too.
