### ISSUE TITLE
DX test getting started experience

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-app-layout#14]
- The component is successfully taken into use (the component is visible in the app) in a frontend starter (from vaadin.com/start) project in under 5 minutes. 
- The component is successfully taken into use (the component is visible in the app) in a Flow starter (from vaadin.com/start) project in under 5 minutes

- 3 test subjects

**Comment by YuriyVaadin** [comment]
Test document: 
 - https://docs.google.com/document/d/1mLDvr_Fh7GATlp0HEcZEZwS_prpX53mz9hq5jsGKVLY/edit#heading=h.etc9jf87123h (for examinator)
 - https://docs.google.com/document/d/1VLcBldQciPPXghwKENvcIFl9w6W2mtg2blQ2VFF6qrQ/edit# (for participant)

Test app:
 - https://drive.google.com/file/d/1OE8bgz0u6gdZ5ZlNiasNm5v55PA1HKdK/view (with bower deps only)
 - https://drive.google.com/file/d/1txyIAgi6xD87bvyc4oL6Weo1ubYARZq-/view (with `polymer-cli`)
