### ISSUE TITLE
Close overlay drawer on navigation

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-app-layout#140]
When using the drawer for navigation then clicking on a link should close the drawer when it is an overlay. The Java version already works like this: https://github.com/vaadin/vaadin-app-layout-flow/blob/master/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/AppLayout.java#L201-L210

**Comment by alvarezguille** [comment]
Currently recommended solution for this is available in [App Layout with links demo](https://cdn.vaadin.com/vaadin-app-layout/2.0.4/demo/#element-basic-demos)

Now that vaadin-router is part of Vaadin (https://github.com/vaadin/platform/pull/883) we should reconsider having this behavior in app layout

**Comment by web-padawan** [comment]
I wouldn't like to introduce hard dependency on vaadin-router API here. 

We could add support for `location-changed` event though, and make it opt-in.

**Comment by web-padawan** [comment]
Marked as "next" because this should be done in 3.x too.

**Comment by web-padawan** [comment]
I'm still in favor of not introducing a hard dependency on the `vaadin-router` here.

However, as we need to fix the root issue, let's consider making a navigation event configurable.
We can still use the event we support by default, but still allow using `vaadin-app-layout` with a different router.

**Comment by Artur-** [comment]
The suggested solution in #180 does not include a hard dependency. It just listens to the vaadin router emitted event.

Do you mean that we would have a string property like `navigationEventName` that would default to `vaadin-router-location-changed ` instead of having a boolean `closeDrawerOnNavigation `?

**Comment by web-padawan** [comment]
Yes, I would like to make the event configurable, similarly to how `vaadin-context-menu` does with [`closeOn`](https://github.com/vaadin/vaadin-context-menu/blob/adad019a1884b3c199b6fc282537b194632d8ec6/src/vaadin-context-menu.js#L319-L328).

Maybe in this case it could be `closeDrawerOn`, and then `setCloseDrawerOn` if we also add Java API.

**Comment by Artur-** [comment]
Updated PR accordingly

**Comment by Artur-** [comment]
Is something else needed for this?

**Comment by web-padawan** [comment]
> The enhancement should have an Acceptance Criteria written to it that states what is needed to be done.

As this is an enhancement, there has to be a comment describing the acceptance criteria by @rolfsmeds

**Comment by rolfsmeds** [comment]
As a user
I want the navigation overlay to close when I navigate to another view
So that I can see the view I just navigated to

## Acceptance criteria
- [ ] 1. Overlay drawer closes automatically upon navigation
- [ ] 1.1 This works by default, without explicit configuration, when used with Vaadin Router
- [ ] 1.2 This can be disabled
- [ ] 1.3 This can be configured to be triggered by any global event, for use without Vaadin Router
- [ ] 2. Overlay drawer is _not_ closed by non-navigation events
- [ ] 3. Non-overlay drawer is _not_ collapsed

## General criteria
- [ ] APIs reviewed
- [ ] UX/DX tests in Alpha

**Comment by jouni** [comment]
Related to this, but probably worth another ticket, is that if you place a Select/Combo Box/Context Menu/etc inside the drawer, the drawer will close when you dismiss the overlay of that component.

**Comment by Artur-** [comment]
As far as I can tell, the PR fulfills all the ACs
