### ISSUE TITLE
[3.0.0-alpha1][doc] "content scrolling": Setting height to 100% can cause printing issues

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-app-layout#148]
I am using content scrolling, [as described in the docs](https://cdn.vaadin.com/vaadin-app-layout/3.0.0-alpha1/index.html), so that my drawer doesn't change length based on the content block. This is causing an issue when printing. Only 1 page's worth of data gets printed. I think that this is due to the print engine for browsers not getting the full height of the rendered shadowDOM before determining the print area.

I was able to fix by adding the following:
```css
@media print {
    html, body {
        height: auto;
    }
}
```
This gives the full sized drawer, and allows for more than one page to print at a time.

Example:
https://glitch.com/~level-perfume-rb4e46pxq

**Comment by web-padawan** [comment]
Thanks for the issue. We never considered printing use case up until now. Not sure if there is an easy way to fix this.

**Comment by moderndeveloperllc** [comment]
I think the use case is rare enough that perhaps just having a note in the docs with the CSS above is good enough.

**Comment by web-padawan** [comment]
Sounds good to me. Feel free to submit a PR if you wish, we should document it.

**Comment by Haprog** [comment]
Instead of needing to set the height twice (by overriding it for print) you could just set the 100% height only for screens. Something like this should work (and not break printing):
```css
@media screen {
    html, body {
        height: 100%;
    }
}
```

I guess it would be good to show this kind of example in the docs or somehow improve the docs so that you don't accidentally break printing without thinking about it.

**Comment by moderndeveloperllc** [comment]
> I guess it would be good to show this kind of example in the docs or somehow improve the docs so that you don't accidentally break printing without thinking about it.

Better solution. I would put in a PR, but not sure where the new docs have gotten off to!

**Comment by web-padawan** [comment]
@moderndeveloperllc the docs for the next generation version are here in JSDoc:

https://github.com/vaadin/vaadin-app-layout/blob/1a09538c87ec99054da7d45b733ffeba46d55cd9/src/vaadin-app-layout.ts#L18

**Comment by web-padawan** [comment]
Closing per https://github.com/vaadin/vaadin-app-layout/pull/149#issuecomment-800217796
