### ISSUE TITLE
Can not customize AppLayout scrollbar in Vaadin V10+

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-app-layout#168]
How can we customize scroolbar style in Vaadin V10+ ?

**Comment by web-padawan** [comment]
The `scrollbar-color` CSS property is only supported by Firefox: https://caniuse.com/mdn-css_properties_scrollbar-color

Closing as there is no cross-browser way for styling scrollbars, and we don't recommend workarounds with partial support.
