### ISSUE TITLE
Hard-coded branding size constrains

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-app-layout#30]
Currently, in the core styles, there are hard-coded size constrains for the branding: `max-width: 20%; max-height: 100%;`.

This could become problematic for certain scenarios, for example, produce accidental text wrapping or downscaling for long images. Applying arbitrary browser scaling for logos often results in a blurry or rough-edged output.

I would suggest to not constrain the developer-provided content whenever possible. Sure any size exceeds and overlaps are problematic, but in case if they are not shown, it is even harder to notice and fix that. The height constrain makes more sense for the navbar content, but the width constrain — looks like it could be removed altogether.

Another idea to consider is to have the navbar `height: auto;`, so that the height is automatically determined from the content. This guarantees to not produce any height overlaps (since the height would be increased instead), and we would have less magic numbers to maintain.

Related issue: the branding image used in the demo does not have a size defined. With the built-in constrains removed, the image is so big, it exceeds the navbar height and overlaps the content. Suggestion: specify width and height attributes on the image with a suitable size in the demo. It is a generally good practice for the developers to follow.

**Comment by jouni** [comment]
Good observations, and I agree.

The Lumo and Material themes probably want to have a fixed height for the navbar, and then having the max-height of the branding content limited sounds reasonable. But for the core styles, maybe it would be best to let the navbar just grow with the content.
