### ISSUE TITLE
Remove unused styling parts and slots

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-app-layout#33]
Remove the styling parts: content, secondary
Remove the slot: secondary

**Comment by DiegoCardoso** [comment]
@jouni about this issue which plans to remove `secondary` part and slot, as you commented in #35, the plan was to leave them, so it raises the question: should it get a proper documentation and a public API for the flow component?

**Comment by jouni** [comment]
Sorry, I have a tendency to ponder “out loud” when I don’t have a good answer available. I was also trying to push the dev team to take ownership and make a decision.

I would postpone adding the extra slot, and proceed according to this task: remove the `secondary` part and slot.

I’m still expecting it to be a relatively high priority to add it back (users will want to place some stuff in the top-right corner of their apps). But like I said in the other comment, we need to decide how we handle it on small viewport sizes. And that might escalate into a lot of additional design (at least it has for me, so far).

**Comment by DiegoCardoso** [comment]
Thanks!

We have an understanding that removing it now and having it back in a new minor would be the best solution, as we can think better about the UX/DX of having this slot. I was willing to get from you if there was stronger reasons for making it to 1.0 instead. 

I'll add an issue to keep track of the secondary slot.
