### ISSUE TITLE
Rename branding to banner

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-app-layout#34]
Update flow integration

**Comment by jouni** [comment]
I think we still need to bikeshed the naming. Do we have any indication that “banner” is any better than “branding”, or better than “logo”, or “app-name” for example?

I was already thinking if we should use more generic names like “start“, “middle” and “end” for the navbar slots. But those would then mean we can’t add semantic meaning to the contents like we currently do with some `aria-role` attributes, so they might not be great either.

**Comment by alvarezguille** [comment]
Let's have a desk by desk short DX survey to decide the naming

**Comment by DiegoCardoso** [comment]
I conducted a small naming research in PD and noticed some other names being raised. 
Most mentioned was `logo`, followed by `branding`, `banner` and `header`. 

It looks like the name itself is not as important as making clear what the property is for in our docs.

We can leave this issue opened to gather more discussion over this subject and come up with which action to take later.
