### ISSUE TITLE
Menu item should support text, href, iron-icon and having an on-click

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-app-layout#4]
- Menu items supports text, href and <iron-icon>
- You can specify on-click for a menu item

**Comment by jouni** [comment]
As discussed previously, we probably want to start by *not* making a custom element for a menu item, but rather use `<vaadin-tabs>` and `<vaadin-tab>` directly.

On the Flow/Java side, further abstraction is probably still a good idea?

**Comment by jouni** [comment]
Not relevant at the moment.
