### ISSUE TITLE
Show how to create a real menu using app-layout

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-app-layout#48]
The demos currently demonstrate that you should create a menu as
```
  <vaadin-tabs slot="menu">
    <vaadin-tab theme="icon-on-top">
      <iron-icon icon="vaadin:home"></iron-icon>
      Page 1
    </vaadin-tab>
    <vaadin-tab theme="icon-on-top">
      <iron-icon icon="vaadin:list"></iron-icon>
      Page 2
    </vaadin-tab>
</vaadin-tabs>
```

While this looks nice, the menu does not work because there are no `<a href>` links in it. If you do add `<a>` tags, you have two options:

1. Wrap the `<vaadin-tab>` element so you have
```
<a>
  <vaadin-tab theme="icon-on-top">
    <iron-icon icon="vaadin:home"></iron-icon>
    Page 1
  </vaadin-tab>
</a>
```
This renders the options correctly, the link works but keyboard navigation (right-left arrows) and highlighting of `vaadin-tabs` no longer works. Navigating between the items using tab works and a menu item can be activated using enter.

2. Wrap the contents of `<vaadin-tab>`
```
<vaadin-tab theme="icon-on-top">
  <a>
    <iron-icon icon="vaadin:home"></iron-icon>
    Page 1
  </a>
</vaadin-tab>
```
This breaks the theme (icon is not on top). Keyboard navigation (left-right) works but selecting/navigating using enter does not.

Please add a demo showing how you should use app-layout in a real application. A workaround using click listeners is not preferable as you then prevent opening the item in a new tab etc.

**Comment by rolfsmeds** [comment]
Bonus for providing a demo of how to use `vaadin-tabs` together with `iron-pages` and `app-route` for proper routing-based navigation.

**Comment by tulioag** [comment]
I tested solution 2 and keyboard navigation seemed to work. I created a PR in  vaadin-tabs to allow icons on top to work in this case.

https://github.com/vaadin/vaadin-tabs/pull/120

**Comment by tulioag** [comment]
A new PR has been created to address this issue. https://github.com/vaadin/vaadin-tabs/pull/121

**Comment by tulioag** [comment]
https://github.com/vaadin/vaadin-tabs/pull/121 is merged. The change will be included in the next major release

**Comment by moderndeveloperllc** [comment]
@tulioag Is this issue still valid? Looks like 2.0 took care of this.

**Comment by tulioag** [comment]
@moderndeveloperllc, this is working now:

```
<vaadin-tab theme="icon-on-top">
  <a router-link href="home">
    <iron-icon icon="vaadin:home"></iron-icon>
    Page 1
  </a>
</vaadin-tab>
```

I believe we still need a demo to be able to close this issue.

**Comment by DiegoCardoso** [comment]
The **App Layout with links** demo show this, doesn't it?

It uses Vaadin Router to manage changing views.

https://cdn.vaadin.com/vaadin-app-layout/2.0.0/demo/#element-basic-demos

**Comment by tulioag** [comment]
Yes, you are right. Closing the issue.
