### ISSUE TITLE
Make part=content take the full available height

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-app-layout#51]
Though the component takes the full height, `part="content"` is not forced to take the available height.

So if developer declares a `<vaadin-app-layout>` like this:

```html
<style>
  .page {
    display: flex;
  }
  
  .content {
    flex: 1; 
  }
  
  .menu {
    background: lightgrey;
    width: 200px;
  }
</style>
<!-- ... -->
<vaadin-app-layout>
  <h3 slot="branding">Application Name</h3>
  <vaadin-tabs slot="menu">
      <vaadin-tab>Page 1</vaadin-tab>
      <vaadin-tab>Page 2</vaadin-tab>
  </vaadin-tabs>
  <div class="page">
    <div class="content">
      Page content
    </div>
    <div class="menu">
      <ul>
        <li>Side menu item</li>
        <li>Side menu item</li>
        <li>Side menu item</li>
        <li>Side menu item</li>
      </ul>
    </div>  
  </div>
</vaadin-app-layout>
```

This would be what they get:

![bumpy-resonance glitch me_ 1](https://user-images.githubusercontent.com/262432/47840903-7fa85e00-ddc0-11e8-9f5a-f6825c3a7ce8.png)

**Comment by jouni** [comment]
I don’t see the issue. The content behaves just as the CSS says it should work. If you want the content to take all the available space, you should use `height. 100%`, right?

**Comment by jouni** [comment]
I agree that it should be possible to be able to make the content (user-defined) use the available space. But we should not force that by default.

**Comment by DiegoCardoso** [comment]
Take a look at [this example](https://glitch.com/edit/#!/cedar-plane?path=index.html:12:19) where the `div.page` is set to `height: 100%`, but still it doesn't grow to take the full height even though when you inspect the `content` part it will show as using it.

**Comment by jouni** [comment]
Yeah, I edited my previous comment and added another one. Hope those clarify my concern.

**Comment by tmattsso** [comment]
What would the expectation of a developer be? can we make it easier for them then having to define a separate bit of boilerplate css? This is after all a very basic use case.

**Comment by jouni** [comment]
> This is after all a very basic use case.

Yes, agreed. And I would expect the expectation of a developer to be that they only need to define the height of the content they provide as `100%` to make it stretch. For example:

```html
<vaadin-app-layout>
  <div class="my-content"></div>
</vaadin-app-layout>

<style>
  .my-content {
    height: 100%;
  }
</style>
```
