### ISSUE TITLE
Mobile responsive?

### ISSUE THREAD

**Issue by lkraav** [vaadin/vaadin-app-layout#58]
Thanks for publishing this. I was expecting more of a result like https://jelements.netlify.com/app-layout but it seems like vaadin-app-layout is still in an "early" phase. Is a mobile responsive iteration in the pipeline here?

**Comment by moderndeveloperllc** [comment]
@lkraav Looks like 2.0 is a bit more full-featured. It's responsive, but I have noticed that when the drawer is in overlay mode (mobile device), it does not close on touch/click. Looks like you will have to add an event listener. Luckily, there are events that fire for on-click, and an attribute to let you know if you are in overly mode.

**Comment by lkraav** [comment]
Yep, I feel like this umbrella issue has been addressed.
