### ISSUE TITLE
Create use case demos to vaadin.com

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-app-layout#6]
- An example with a large viewport
- An example with a small viewport
- An example with a large number of menu items
- An example with text as the logo/branding
- An example with an image as the logo/branding

**Comment by alvarezguille** [comment]
Either make a PR to `vaadin-demo-helpers` making the address bar visibility configurable, or theme the `vaadin-demo-snippet` element to hide the address bar.

**Comment by alexberazouski** [comment]
Fixed in #24
