### ISSUE TITLE
App Layout with drawer slot

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-app-layout#62]
Next major version for `vaadin-app-layout`
Includes slots for drawer and navigation bar
Has API to change precedence mode between drawer and navigation bar as shown in following mockups:
* Full height drawer
![image](https://user-images.githubusercontent.com/9820084/55231849-7cf54c00-522c-11e9-98a2-c6424e7acd36.png)
* Full width navigation bar
![image](https://user-images.githubusercontent.com/9820084/55231877-8bdbfe80-522c-11e9-8ba4-1f2098cfa0ac.png)

**Comment by alvarezguille** [comment]
[2.0.0-beta1](https://github.com/vaadin/vaadin-app-layout/releases/tag/v2.0.0-beta1) released today

**Comment by kyberorg** [comment]
@alvarezguille how to change to “ Full width navigation bar” mode in AppLayout 2?
