### ISSUE TITLE
Menu interfers with iPhone X swipebar

### ISSUE THREAD

**Issue by cedricaebi** [vaadin/vaadin-app-layout#72]
When installed as a PWA the menu-items are lying below the iPhone X swipebar, and therefore the menu cant be scrolled horizontally

**Comment by oluwasayo** [comment]
Not reproducible on master. It means this ticket should be resolved on next release.

**Comment by web-padawan** [comment]
I tried `vaadin-app-layout` on iPhone X recently and could not reproduce this either.

Closing as invalid. If this is still a problem, please submit a new issue, preferably with a screenshot.
