### ISSUE TITLE
Minor Material theme UI tweak

### ISSUE THREAD

**Issue by anezthes** [vaadin/vaadin-app-layout#98]
👎 
![before](https://user-images.githubusercontent.com/7125728/57913281-f278b280-7894-11e9-835b-56e6809e58ac.png)

👍 
![after](https://user-images.githubusercontent.com/7125728/57913293-f9072a00-7894-11e9-83fe-55fab212bbe4.png)
```
[part="navbar"] {
  z-index: 1;
}
```

**Comment by ericmartinezr** [comment]
I was about to open an issue reporting for the same problem. Found nothing on *-flow repo. Thanks for the workaround 👍
